### ISSUE TITLE
Bad reference to instance data in script nginx-ha-notify

### ISSUE THREAD

**Issue by julienmary** [nginxinc/aws-ha-elastic-ip#2]
On line 27 and 35, in the url, instance-data should be replaced by 169.254.169.254, as instance data is unlikely to be resolved.

**Comment by dfosborne2** [comment]
This has still not been fixed. Plus they fail to mention that you need to setup protocol 112 for vrrp in a security group.  Just a couple of reasons why we are dumping nginx plus as soon as our contract is up.

**Comment by ghost** [comment]
Can we please have this fixed?

**Comment by thresheek** [comment]
I've opened a PR for this to be fixed at: https://github.com/nginxinc/aws-ha-elastic-ip/pull/5
