### ISSUE TITLE
Update solution requirement for API call

### ISSUE THREAD

**Issue by ghost** [nginxinc/aws-ha-elastic-ip#4]
If a standby node does not have a public IP assigned, a private vpc-endpoint must be created, otherwise its API call to assign Public IP to itself as it transitions to the active node will not reach Internet facing API endpoint.

Request to update the solution README to reflect this requirement.

**Comment by thresheek** [comment]
Wouldnt it mean that the prior `aws ec2` api calls will also fail if the node does not have a connectivity to an API service?

**Comment by ghost** [comment]
I say so as API call can't be routed to public endpoint without a public IP. Customer has tried this and said that private endpoint is needed in both AZ.
